POST http://localhost:8080/api/players
Accept: application/json
Content-Type: application/json

{
  "name": "Michael",
  "dateOfBirth": "2002-12-01",
  "playerPosition": "GOALKEEPER"

}

###
GET http://localhost:8080/api/players
Accept: application/json

###

DELETE http://localhost:8080/api/players/5100

