POST http://localhost:8080/api/car-sellers
Content-Type: application/json

{
  "sellerName":"Best Cars"
}

###
GET http://localhost:8080/api/cars/brands
Accept: application/json

###
POST http://localhost:8080/api/cars/1/kilometer-states
Content-Type: application/json

{
  "km": 124
}

###
GET http://localhost:8080/api/cars?brand=Toyota
Accept: application/json

###
POST http://localhost:8080/api/cars
Accept: application/json
Content-Type: application/json

{
  "brand": "Toyota",
  "type": "Swift",
  "age": 5,
  "carCondition": "NORMAL",
  "km": -100
}

###
